-- ---------------------------------------------------------------------------
-- שם טוב — phase 5: verified Hebrew meanings, replacing the seed catalogue.
--
-- Run once in the Supabase SQL Editor, after 2026-09-shem-tov-phase4-catalogue.sql.
--
-- What this does, and why it's an upsert rather than a wipe-and-reinsert:
--
-- The new curated dataset shares 176 of its 200 names with the phase-4
-- seed, and differs on 24. A family may already have voted on a phase-4
-- catalogue name — deleting and reinserting all 200 rows would generate new
-- ids for names that already exist, and CASCADE-delete any votes already
-- cast on them. Instead this UPSERTs by name text: the 176 overlapping
-- names keep their existing id (and therefore keep any votes already cast
-- on them) while every column gets refreshed to the new, verified values;
-- the 24 new names are inserted fresh.
--
-- The 24 phase-4 names that are NOT in the new curated set are then
-- deleted — the task calls for the CSV to be the source of truth, and
-- keeping stale, non-curated rows around contradicts that. Read the
-- warning above the DELETE below before running this migration: if any
-- family has already voted on one of those 24 names, this migration
-- removes those votes along with the name (foreign-key CASCADE). Given how
-- recently the catalogue was first seeded, that's expected to affect zero
-- real votes — but it is a real, if unlikely, side effect worth knowing
-- about before you run this.
-- ---------------------------------------------------------------------------

alter table public.names
  add column if not exists meaning_he         text,
  add column if not exists greek              boolean not null default false,
  add column if not exists meaning_source      text,
  add column if not exists meaning_confidence  text
    check (meaning_confidence is null or meaning_confidence in ('verified', 'uncertain'));

create index if not exists names_greek_idx on public.names (id) where greek;

-- Needed as the ON CONFLICT arbiter below: catalogue names (family_id is
-- null) must be unique by text so an upsert can find "the same name" to
-- update; a family's own suggestions (family_id not null) are untouched by
-- this and may still duplicate any text freely, same as before.
create unique index if not exists names_catalogue_text_unique
  on public.names (text) where family_id is null;

insert into public.names (
  text, gender, origin, length, syllables,
  biblical, hebrew, israeli, international, arabic, european, greek,
  meaning_love, meaning_nature, meaning_light, meaning_strength, meaning_joy, meaning_freedom,
  style_classic, style_modern, style_unique, style_soft, style_traditional, style_vintage,
  popularity, popularity_score,
  short, easy_in_english, works_internationally,
  starts_with, ends_with,
  meaning_he, meaning_source, meaning_confidence
)
values
  ('אביגיל', 'girl', 'Biblical;Hebrew', 6, 3, true, true, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, true, false, 'popular', 4, false, false, false, 'א', 'ל', 'שמחת האב', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אדם', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, true, false, 'א', 'ם', 'אדם; בן אנוש; עפר האדמה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אגם', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'popular', 4, true, false, false, 'א', 'ם', 'אגם; גוף מים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אדר', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'א', 'ר', 'חודש אדר; הדר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אורי', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'א', 'י', 'האור שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אור', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'א', 'ר', 'אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אורן', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'א', 'ן', 'עץ אורן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אייל', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, false, 'less_common', 3, true, false, false, 'א', 'ל', 'אַיָּל; צבי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('איילה', 'girl', 'Hebrew;Israeli', 5, 3, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, false, 'less_common', 3, false, false, false, 'א', 'ה', 'נקבת האייל; צבייה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('איתן', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'א', 'ן', 'חזק; איתן; יציב', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלון', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'א', 'ן', 'עץ אלון', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלה', 'girl', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'א', 'ה', 'עץ אלה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלי', 'unisex', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'א', 'י', 'אלוהיי; האל שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אליהו', 'boy', 'Biblical;Hebrew', 5, 4, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, false, false, false, 'א', 'ו', 'אלוהיי הוא יהוה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלעד', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'א', 'ד', 'אל עד; אל נצחי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אמיר', 'boy', 'Hebrew;Arabic', 4, 2, false, true, false, false, true, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'א', 'ר', 'נסיך; מנהיג', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אריאל', 'unisex', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, 'popular', 4, false, true, false, 'א', 'ל', 'אריה האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ארי', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'א', 'י', 'אריה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אריה', 'boy', 'Biblical;Hebrew', 4, 3, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'א', 'ה', 'אריה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ארז', 'boy', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'א', 'ז', 'עץ ארז', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אסף', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'א', 'ף', 'אסף; כינס', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אופק', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'popular', 4, true, false, false, 'א', 'ק', 'קו האופק', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אופיר', 'unisex', 'Biblical;Hebrew', 5, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, false, false, false, 'א', 'ר', 'שם מקראי של חבל ארץ/מקום; מזוהה במסורת עם זהב', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אפרת', 'girl', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'א', 'ת', 'פורה; שופעת', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('בר', 'unisex', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ב', 'ר', 'בן; דגן/תבואה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ברק', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ב', 'ק', 'ברק; הבזק אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('בתיה', 'girl', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'ב', 'ה', 'בת האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('בתאל', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, 'less_common', 3, true, false, false, 'ב', 'ל', 'בת האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גאיה', 'girl', 'Greek;International', 4, 2, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'ג', 'ה', 'ארץ; אדמה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('גדי', 'boy', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'ג', 'י', 'מזל גדי; גדיא', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גיא', 'boy', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ג', 'א', 'עמק; בקעה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גיל', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'ג', 'ל', 'שמחה; חדווה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דניאל', 'unisex', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, false, false, false, 'ד', 'ל', 'אלוהים הוא שופטי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דנה', 'girl', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ד', 'ה', 'דנה; שופטת', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דוד', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'ד', 'ד', 'אהוב; דוד', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דור', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ד', 'ר', 'דור; תקופה; דור אנושי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דביר', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'ד', 'ר', 'דביר; מקום מקודש במקדש', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דרור', 'unisex', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, true, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'ד', 'ר', 'חופש; ציפור דרור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('הדס', 'girl', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ה', 'ס', 'הדס; עץ הדס', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('הדר', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'ה', 'ר', 'הוד; פאר; הדר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('הלל', 'unisex', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, 'less_common', 3, true, false, false, 'ה', 'ל', 'שבח; תהילה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('הראל', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ה', 'ל', 'הר האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('הילה', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, true, false, false, true, false, false, 'less_common', 3, true, false, false, 'ה', 'ה', 'הילה; זוהר סביב מקור אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ורד', 'girl', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, true, 'less_common', 3, true, false, false, 'ו', 'ד', 'ורד; פרח', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('זוהר', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, 'popular', 4, true, false, false, 'ז', 'ר', 'זוהר; ברק; אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('זיו', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ז', 'ו', 'זוהר; אור; הדר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('חגי', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'ח', 'י', 'חג שלי; חג', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('חיים', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'ח', 'ם', 'חיים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('טל', 'unisex', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ט', 'ל', 'טל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('טלי', 'girl', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'ט', 'י', 'טל שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יאיר', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'י', 'ר', 'יאיר; יאיר אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יעל', 'girl', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'י', 'ל', 'יעל; חיית הרים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יובל', 'unisex', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'י', 'ל', 'יובל; זרם מים; קרן איל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יהלי', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'י', 'י', 'יהלום שלי; צורה מודרנית הקשורה ליהל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יהונתן', 'boy', 'Biblical;Hebrew', 6, 4, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, false, false, false, 'י', 'ן', 'יהוה נתן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יונתן', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, false, false, false, 'י', 'ן', 'יהוה נתן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יואב', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'י', 'ב', 'יהוה הוא אב', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יוסף', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'י', 'ף', 'יוסיף; יגדיל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יסמין', 'girl', 'Arabic;International', 5, 3, false, false, false, true, true, false, false, false, true, false, false, false, false, false, false, false, true, false, false, 'less_common', 3, false, false, false, 'י', 'ן', 'יסמין; פרח היסמין', 'Behind the Name / established dictionary etymology', 'verified'),
  ('ליאור', 'unisex', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, 'popular', 4, false, false, false, 'ל', 'ר', 'לי אור; האור שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ליבי', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'ל', 'י', 'ליבי; הלב שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ליה', 'girl', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ל', 'ה', 'שם מקראי; מקור המשמעות אינו ודאי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('לב', 'boy', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'ל', 'ב', 'לב', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('לי', 'unisex', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ל', 'י', 'לי; שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מיכאל', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, false, false, false, 'מ', 'ל', 'מי כאל?', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מיכל', 'girl', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'מ', 'ל', 'מי כאל?', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מור', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'מ', 'ר', 'מור; שרף/בושם מצמח המור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נועה', 'girl', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'נ', 'ה', 'תנועה; שם מקראי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נועם', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'נ', 'ם', 'נעימות; חן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נבו', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'נ', 'ו', 'שם הר/מקום במקרא; האטימולוגיה אינה ודאית', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('נטע', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'popular', 4, true, false, false, 'נ', 'ע', 'נטע; צמח צעיר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נויה', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'נ', 'ה', 'יופי; נוי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נעמי', 'girl', 'Biblical;Hebrew', 4, 3, true, true, false, false, false, false, false, false, false, false, false, true, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'נ', 'י', 'נעימות; נועם', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עדי', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ע', 'י', 'תכשיט; עדי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עידן', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ע', 'ן', 'תקופה; זמן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עמית', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ע', 'ת', 'חבר; עמית', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עמנואל', 'unisex', 'Biblical;Hebrew', 6, 4, true, true, false, false, false, false, false, false, true, false, false, false, false, false, false, false, false, true, false, 'less_common', 3, false, false, false, 'ע', 'ל', 'אלוהים עמנו', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ענבר', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'popular', 4, true, false, false, 'ע', 'ר', 'ענבר; שרף מאובן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עומר', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ע', 'ר', 'עומר; אלומת תבואה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עומרי', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, false, false, false, 'ע', 'י', 'עומר שלי; עומר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עופרי', 'unisex', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, false, false, false, 'ע', 'י', 'עופר שלי; עופר/אייל צעיר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רוני', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'ר', 'י', 'רוני; שמחתי; שירי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רון', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ר', 'ן', 'שירה; שמחה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רפאל', 'boy', 'Biblical;Hebrew', 4, 3, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, 'less_common', 3, true, false, false, 'ר', 'ל', 'אלוהים ריפא', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רומי', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ר', 'י', 'רום; נעלה; רם', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רות', 'girl', 'Biblical;Hebrew', 3, 1, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'ר', 'ת', 'רֵעוּת; חברה; משמעות השם אינה ודאית לחלוטין', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('שחר', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ש', 'ר', 'שחר; עלות הבוקר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שקד', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'popular', 4, true, false, false, 'ש', 'ד', 'שקד; עץ השקד', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שירה', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, true, false, true, false, false, true, false, false, 'popular', 4, true, false, false, 'ש', 'ה', 'שיר; שירה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שירי', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'ש', 'י', 'השיר שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תבור', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'ת', 'ר', 'הר תבור; שם גאוגרפי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תמר', 'girl', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'ת', 'ר', 'תמר; עץ תמר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תום', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ת', 'ם', 'תום; שלמות; תמימות', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תומר', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ת', 'ר', 'תמר; עץ תמר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אבנר', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, true, false, 'rare', 2, true, false, false, 'א', 'ר', 'אבי הוא נר; אבי הוא אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אבישי', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, 'less_common', 3, false, false, false, 'א', 'י', 'אבי ישי; אב + ישי; פירוש השם אינו ודאי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('אוריאל', 'boy', 'Biblical;Hebrew', 6, 4, true, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, false, 'less_common', 3, false, false, false, 'א', 'ל', 'אור האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלכס', 'unisex', 'International;Greek', 4, 2, false, false, false, true, false, false, true, false, true, false, true, false, false, false, true, false, false, false, false, 'less_common', 3, true, true, true, 'א', 'ס', 'מגן; מגן על האנשים', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אמילי', 'girl', 'International;Latin', 5, 3, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'popular', 4, false, true, true, 'א', 'י', 'שם ממשפחת Aemilius; מזוהה עם חריצות/תחרותיות', 'Behind the Name / established dictionary etymology', 'verified'),
  ('בארי', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'ב', 'י', 'באר שלי; באר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('בן', 'boy', 'Biblical;Hebrew', 2, 1, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'popular', 4, true, false, false, 'ב', 'ן', 'בן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('בנימין', 'boy', 'Biblical;Hebrew', 6, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, false, false, false, 'ב', 'ן', 'בן ימין; בן היד הימנית', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גפן', 'unisex', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'ג', 'ן', 'גפן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גילי', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'ג', 'י', 'גילי; שמחתי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('יהב', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'י', 'ב', 'מתנה; נתינה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('לוטם', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'ל', 'ם', 'לוטם; צמח', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('לוטן', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, 'rare', 2, true, false, false, 'ל', 'ן', 'שם מקראי; קשור לשורש לוט/כיסוי לפי מסורות אטימולוגיות', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מאי', 'unisex', 'International;European', 3, 1, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'מ', 'י', 'שם בינלאומי; המשמעות תלויה במקור', 'Behind the Name / established dictionary etymology', 'uncertain'),
  ('מילי', 'girl', 'International;European', 4, 2, false, false, false, true, false, true, false, false, false, false, false, false, false, false, true, false, true, false, false, 'rare', 2, true, false, false, 'מ', 'י', 'קיצור של שמות כמו אמיליה/אמילי; המשמעות תלויה בשם המקור', 'Behind the Name / established dictionary etymology', 'verified'),
  ('סהר', 'unisex', 'Hebrew;Arabic', 3, 2, false, true, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ס', 'ר', 'סהר; ירח בצורת קשת', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('סיוון', 'girl', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, false, false, false, 'ס', 'ן', 'חודש סיוון', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עילאי', 'boy', 'Hebrew;Israeli', 5, 3, false, true, true, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, 'less_common', 3, false, false, false, 'ע', 'י', 'עילאי; עליון; נעלה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עילי', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ע', 'י', 'עילי; עליון', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רז', 'unisex', 'Aramaic;Hebrew', 2, 1, false, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'ר', 'ז', 'סוד; רז', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ריף', 'unisex', 'International;Hebrew', 3, 1, false, true, false, true, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'ר', 'ף', 'שונית; reef', 'Behind the Name / established dictionary etymology', 'verified'),
  ('רום', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'ר', 'ם', 'גובה; רוממות; נעלה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עטרה', 'girl', 'Biblical;Hebrew', 4, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'rare', 2, true, false, false, 'ע', 'ה', 'כתר; עטרה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('כתר', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, 'rare', 2, true, false, false, 'כ', 'ר', 'כתר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נעם', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, true, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'נ', 'ם', 'נעימות; חן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אביטל', 'girl', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, false, false, false, 'א', 'ל', 'אבי הוא טל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אפרים', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'rare', 2, false, false, false, 'א', 'ם', 'פורה; מפרה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אסתר', 'girl', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'א', 'ר', 'ככל הנראה הדס/כוכב; האטימולוגיה שנויה במחלוקת', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('רותם', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ר', 'ם', 'רותם; שיח מדברי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('כרמל', 'unisex', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'כ', 'ל', 'כרמל; כרם/אדמה פורייה; גם הר הכרמל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('כנרת', 'girl', 'Hebrew;Israeli', 4, 3, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, 'rare', 2, true, false, false, 'כ', 'ת', 'כנרת; שם האגם/הים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ים', 'unisex', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'י', 'ם', 'ים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גל', 'unisex', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ג', 'ל', 'גל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גלי', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'ג', 'י', 'הגל שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אורין', 'unisex', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, true, false, false, false, 'rare', 2, false, false, false, 'א', 'ן', 'אור; צורה מודרנית, המשמעות האטימולוגית אינה חד-משמעית', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ליב', 'unisex', 'Hebrew;International', 3, 1, false, true, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'ל', 'ב', 'לב; heart', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אופל', 'unisex', 'International;Hebrew', 4, 2, false, true, false, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'א', 'ל', 'אופל; אבן חן', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אביה', 'unisex', 'Biblical;Hebrew', 4, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'less_common', 3, true, false, false, 'א', 'ה', 'אבי הוא יהוה/אבי הוא האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אבישג', 'girl', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'rare', 2, false, false, false, 'א', 'ג', 'אבי הוא שגג/שג; האטימולוגיה אינה ודאית', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('אורית', 'girl', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, true, false, false, true, false, false, 'less_common', 3, false, false, false, 'א', 'ת', 'אור שלי/אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אילן', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'א', 'ן', 'עץ', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אילנה', 'girl', 'Hebrew;Israeli', 5, 3, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, false, false, false, 'א', 'ה', 'עץ; אילן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אמונה', 'girl', 'Hebrew;Israeli', 5, 3, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, 'rare', 2, false, false, false, 'א', 'ה', 'אמונה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ברוך', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'rare', 2, true, false, false, 'ב', 'ך', 'מבורך', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('דולב', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'ד', 'ב', 'דולב; עץ', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מתן', 'boy', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'מ', 'ן', 'מתנה; נתינה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נתן', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, 'popular', 4, true, false, false, 'נ', 'ן', 'נתן; נתינה; הוא נתן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רועי', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'ר', 'י', 'רועי; הרועה שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שגיא', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'ש', 'א', 'נשגב; רם; גדול', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('סער', 'boy', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ס', 'ר', 'סערה; רוח סערה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('גלעד', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'ג', 'ד', 'גל עד; גל/מצבה לעדות', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נדב', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'נ', 'ב', 'נדיב; מתנדב; נותן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עוז', 'boy', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ע', 'ז', 'כוח; עוצמה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עוזי', 'boy', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, true, false, false, true, true, false, false, false, false, 'rare', 2, true, false, false, 'ע', 'י', 'עוז שלי; כוחי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שי', 'unisex', 'Hebrew;Israeli', 2, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ש', 'י', 'מתנה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אוריה', 'unisex', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, true, false, false, false, false, true, false, false, true, false, 'less_common', 3, false, false, false, 'א', 'ה', 'אור יהוה; אור האל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אחינועם', 'girl', 'Biblical;Hebrew', 7, 4, true, true, false, false, false, false, false, false, false, false, false, true, false, false, false, true, false, true, false, 'rare', 2, false, false, false, 'א', 'ם', 'אח/אחי הוא נועם', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אורלי', 'girl', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, true, false, false, true, false, false, 'less_common', 3, false, false, false, 'א', 'י', 'האור שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלמוג', 'unisex', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, false, false, false, 'א', 'ג', 'אלמוג; coral', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ניר', 'boy', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'נ', 'ר', 'שדה חרוש', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('ניב', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'נ', 'ב', 'פרי; ביטוי/שפה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נוער', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'נ', 'ר', 'נעורים; youth', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('פלג', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'פ', 'ג', 'פלג; ערוץ מים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שוהם', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, false, false, 'ש', 'ם', 'אבן חן; אוניקס', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שלו', 'boy', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'ש', 'ו', 'שלו; רגוע; שלֵו', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שמשון', 'boy', 'Biblical;Hebrew', 5, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, 'rare', 2, false, false, false, 'ש', 'ן', 'שמש; קשור לשמש', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('צבי', 'boy', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, true, false, false, 'צ', 'י', 'צבי; אייל', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אביב', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'א', 'ב', 'אביב; עונת האביב', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עדן', 'unisex', 'Biblical;Hebrew', 3, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'ע', 'ן', 'עדן; עונג; גן עדן', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מעיין', 'unisex', 'Hebrew;Israeli', 5, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, true, false, false, false, false, 'popular', 4, false, false, false, 'מ', 'ן', 'מעיין; מקור מים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('קשת', 'unisex', 'Hebrew;Israeli', 3, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'less_common', 3, true, false, false, 'ק', 'ת', 'קשת; rainbow', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('נוגה', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, false, false, 'נ', 'ה', 'זוהר; בהירות; נוגה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('שיר', 'unisex', 'Hebrew;Israeli', 3, 1, false, true, true, false, false, false, false, false, false, false, false, true, false, false, true, false, false, false, false, 'popular', 4, true, false, false, 'ש', 'ר', 'שיר', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תאיר', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'ת', 'ר', 'תאיר; תביא אור', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תכלת', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, 'rare', 2, true, false, false, 'ת', 'ת', 'צבע תכלת', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('תדהר', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, 'rare', 2, true, false, false, 'ת', 'ר', 'תדהר; עץ', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('רקפת', 'girl', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, true, false, false, false, 'rare', 2, true, false, false, 'ר', 'ת', 'רקפת; פרח', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('כליל', 'unisex', 'Hebrew;Israeli', 4, 2, false, true, true, false, false, false, false, false, true, false, false, false, false, false, false, true, false, false, false, 'rare', 2, true, false, false, 'כ', 'ל', 'כליל; שלם; תמים', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('טליה', 'girl', 'Hebrew;Israeli', 4, 3, false, true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, 'less_common', 3, true, false, false, 'ט', 'ה', 'טל האל; טליה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('מיכאלה', 'girl', 'Biblical;Hebrew;International', 6, 4, true, true, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'less_common', 3, false, false, false, 'מ', 'ה', 'מי כאל?', 'Behind the Name / established dictionary etymology', 'verified'),
  ('גבריאל', 'boy', 'Biblical;Hebrew;International', 6, 3, true, true, false, true, false, false, false, false, true, false, true, false, false, true, false, false, false, false, false, 'popular', 4, false, false, false, 'ג', 'ל', 'אלוהים הוא כוחי', 'Behind the Name / established dictionary etymology', 'verified'),
  ('מלאכי', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, false, false, false, false, false, false, true, false, false, true, false, 'less_common', 3, false, false, false, 'מ', 'י', 'המלאך שלי; שליח שלי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('אלישע', 'boy', 'Biblical;Hebrew', 5, 3, true, true, false, false, false, false, false, false, true, false, false, false, false, true, false, false, false, true, false, 'less_common', 3, false, false, false, 'א', 'ע', 'אלוהים הוא ישועה', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('איתי', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'א', 'י', 'איתי; עמי; איתי', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'verified'),
  ('עידו', 'boy', 'Biblical;Hebrew', 4, 2, true, true, false, false, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, false, false, 'ע', 'ו', 'שם מקראי; משמעות אטימולוגית אינה ודאית', 'Hebrew Names: 200+ Most Popular Israeli Names / 200+ Hebrew Boy Names', 'uncertain'),
  ('סופיה', 'girl', 'Greek;International', 5, 3, false, false, false, true, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, 'popular', 4, false, true, true, 'ס', 'ה', 'חוכמה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('קלרה', 'girl', 'Latin;International', 4, 2, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'less_common', 3, true, true, true, 'ק', 'ה', 'בהירה; צלולה; מפורסמת', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אמה', 'girl', 'Germanic;International', 3, 2, false, false, false, true, false, false, false, false, false, false, false, false, false, true, true, false, false, false, false, 'popular', 4, true, true, true, 'א', 'ה', 'שלמה; אוניברסלית; גדולה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אליס', 'girl', 'Germanic;International', 4, 2, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'less_common', 3, true, true, true, 'א', 'ס', 'אצילות; ממעמד אצילי', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אמיליה', 'girl', 'Germanic;International', 6, 4, false, false, false, true, false, false, false, false, false, false, false, false, false, true, false, false, false, false, false, 'popular', 4, false, false, false, 'א', 'ה', 'עבודה; חריצות; צורה של Amalia', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אוליביה', 'girl', 'Latin;International', 7, 4, false, false, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, 'popular', 4, false, true, true, 'א', 'ה', 'זית; עץ הזית', 'Behind the Name / established dictionary etymology', 'verified'),
  ('לונה', 'girl', 'Latin;International', 4, 2, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, true, true, 'ל', 'ה', 'הירח', 'Behind the Name / established dictionary etymology', 'verified'),
  ('לילי', 'girl', 'Latin;International', 4, 2, false, false, false, true, false, false, false, false, true, false, false, false, false, false, false, false, true, false, false, 'less_common', 3, true, true, true, 'ל', 'י', 'שושן; פרח המסמל טוהר', 'Behind the Name / established dictionary etymology', 'verified'),
  ('ליאו', 'boy', 'Latin;International', 4, 2, false, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, 'popular', 4, true, true, true, 'ל', 'ו', 'אריה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('ליאון', 'boy', 'Greek;International', 5, 2, false, false, false, true, false, false, true, false, false, false, true, false, false, true, false, false, false, false, false, 'less_common', 3, false, true, true, 'ל', 'ן', 'אריה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('ליאם', 'boy', 'Irish;International', 4, 2, false, false, false, true, false, false, false, false, false, false, true, false, false, false, true, false, false, false, false, 'popular', 4, true, true, true, 'ל', 'ם', 'צורה מקוצרת של William; מגן נחוש/רצון', 'Behind the Name / established dictionary etymology', 'verified'),
  ('מקס', 'boy', 'Latin;International', 3, 1, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, false, false, false, 'popular', 4, true, true, true, 'מ', 'ס', 'קיצור של Maximilian/Maximus; הגדול ביותר', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אנה', 'girl', 'Hebrew;Greek;International', 3, 2, false, true, false, true, false, false, true, false, false, false, false, false, false, true, false, false, false, false, false, 'popular', 4, true, true, true, 'א', 'ה', 'חסד; חן', 'Behind the Name / established dictionary etymology', 'verified'),
  ('בלה', 'girl', 'Italian;International', 3, 2, false, false, false, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, 'less_common', 3, true, true, true, 'ב', 'ה', 'יפה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אווה', 'girl', 'Hebrew;International', 4, 2, false, true, false, true, false, false, false, false, true, false, false, false, false, true, false, false, false, false, false, 'less_common', 3, true, true, true, 'א', 'ה', 'חיים; חיה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('אוליבר', 'boy', 'Latin;International', 6, 3, false, false, false, true, false, false, false, false, true, false, false, false, false, true, true, false, false, false, false, 'popular', 4, false, true, true, 'א', 'ר', 'זית; עץ הזית', 'Behind the Name / established dictionary etymology', 'verified'),
  ('לוקה', 'unisex', 'Latin;International', 4, 2, false, false, false, true, false, false, false, false, true, false, false, false, false, false, true, true, false, false, false, 'popular', 4, true, true, true, 'ל', 'ה', 'מאנשים מלוקאניה; מקור גאוגרפי', 'Behind the Name / established dictionary etymology', 'verified'),
  ('מילה', 'girl', 'Slavic;International', 4, 2, false, false, false, true, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'popular', 4, true, false, false, 'מ', 'ה', 'חביבה; יקרה; שורש סלאבי mil', 'Behind the Name / established dictionary etymology', 'verified'),
  ('נואה', 'unisex', 'Hebrew;International', 4, 2, false, true, false, true, false, false, false, false, false, false, false, false, false, false, true, false, true, false, false, 'less_common', 3, true, true, true, 'נ', 'ה', 'נֹחַ; מנוחה; נחמה', 'Behind the Name / established dictionary etymology', 'verified'),
  ('ניקו', 'unisex', 'Greek;International', 4, 2, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, 'less_common', 3, true, true, true, 'נ', 'ו', 'ניצחון העם', 'Behind the Name / established dictionary etymology', 'verified'),
  ('תיאה', 'girl', 'Greek;International', 4, 2, false, false, false, true, false, false, true, false, false, false, false, false, false, false, true, false, false, false, false, 'rare', 2, true, false, false, 'ת', 'ה', 'אלוהית; אלה', 'Behind the Name / established dictionary etymology', 'verified')
on conflict (text) where family_id is null
do update set
  gender = excluded.gender,
  origin = excluded.origin,
  length = excluded.length,
  syllables = excluded.syllables,
  biblical = excluded.biblical,
  hebrew = excluded.hebrew,
  israeli = excluded.israeli,
  international = excluded.international,
  arabic = excluded.arabic,
  european = excluded.european,
  greek = excluded.greek,
  meaning_love = excluded.meaning_love,
  meaning_nature = excluded.meaning_nature,
  meaning_light = excluded.meaning_light,
  meaning_strength = excluded.meaning_strength,
  meaning_joy = excluded.meaning_joy,
  meaning_freedom = excluded.meaning_freedom,
  style_classic = excluded.style_classic,
  style_modern = excluded.style_modern,
  style_unique = excluded.style_unique,
  style_soft = excluded.style_soft,
  style_traditional = excluded.style_traditional,
  style_vintage = excluded.style_vintage,
  popularity = excluded.popularity,
  popularity_score = excluded.popularity_score,
  short = excluded.short,
  easy_in_english = excluded.easy_in_english,
  works_internationally = excluded.works_internationally,
  starts_with = excluded.starts_with,
  ends_with = excluded.ends_with,
  meaning_he = excluded.meaning_he,
  meaning_source = excluded.meaning_source,
  meaning_confidence = excluded.meaning_confidence;

-- ---------------------------------------------------------------------------
-- Extend family_name_rankings with the new meaning fields, so the ranking
-- screen's cards can show the real curated meaning too, not just browse.
-- CREATE OR REPLACE VIEW with the same column set plus two more at the end
-- is safe — existing columns keep their position, nothing that already
-- reads this view breaks.
-- ---------------------------------------------------------------------------

create or replace view public.family_name_rankings
with (security_invoker = true) as
select
  v.family_id,
  n.id                       as name_id,
  n.text,
  n.gender,
  n.origin,
  n.family_id                as suggested_for_family_id,
  count(distinct v.user_id)  as vote_count,
  max(v.created_at)          as last_voted_at,
  n.meaning_he,
  n.meaning_confidence
from public.name_votes v
join public.names n on n.id = v.name_id
group by v.family_id, n.id, n.text, n.gender, n.origin, n.family_id, n.meaning_he, n.meaning_confidence;

grant select on public.family_name_rankings to authenticated;


-- ---------------------------------------------------------------------------
-- Remove catalogue names that are NOT in the curated set above.
--
-- WARNING: this CASCADE-deletes any votes already cast on one of these 24
-- names (name_votes.name_id references names.id on delete cascade). See the
-- note at the top of this file.
-- ---------------------------------------------------------------------------

delete from public.names
where family_id is null
  and text not in (
    'אביגיל', 'אדם', 'אגם', 'אדר', 'אורי', 'אור', 'אורן', 'אייל', 'איילה', 'איתן', 'אלון', 'אלה', 'אלי', 'אליהו', 'אלעד', 'אמיר', 'אריאל', 'ארי', 'אריה', 'ארז', 'אסף', 'אופק', 'אופיר', 'אפרת', 'בר', 'ברק', 'בתיה', 'בתאל', 'גאיה', 'גדי', 'גיא', 'גיל', 'דניאל', 'דנה', 'דוד', 'דור', 'דביר', 'דרור', 'הדס', 'הדר', 'הלל', 'הראל', 'הילה', 'ורד', 'זוהר', 'זיו', 'חגי', 'חיים', 'טל', 'טלי', 'יאיר', 'יעל', 'יובל', 'יהלי', 'יהונתן', 'יונתן', 'יואב', 'יוסף', 'יסמין', 'ליאור', 'ליבי', 'ליה', 'לב', 'לי', 'מיכאל', 'מיכל', 'מור', 'נועה', 'נועם', 'נבו', 'נטע', 'נויה', 'נעמי', 'עדי', 'עידן', 'עמית', 'עמנואל', 'ענבר', 'עומר', 'עומרי', 'עופרי', 'רוני', 'רון', 'רפאל', 'רומי', 'רות', 'שחר', 'שקד', 'שירה', 'שירי', 'תבור', 'תמר', 'תום', 'תומר', 'אבנר', 'אבישי', 'אוריאל', 'אלכס', 'אמילי', 'בארי', 'בן', 'בנימין', 'גפן', 'גילי', 'יהב', 'לוטם', 'לוטן', 'מאי', 'מילי', 'סהר', 'סיוון', 'עילאי', 'עילי', 'רז', 'ריף', 'רום', 'עטרה', 'כתר', 'נעם', 'אביטל', 'אפרים', 'אסתר', 'רותם', 'כרמל', 'כנרת', 'ים', 'גל', 'גלי', 'אורין', 'ליב', 'אופל', 'אביה', 'אבישג', 'אורית', 'אילן', 'אילנה', 'אמונה', 'ברוך', 'דולב', 'מתן', 'נתן', 'רועי', 'שגיא', 'סער', 'גלעד', 'נדב', 'עוז', 'עוזי', 'שי', 'אוריה', 'אחינועם', 'אורלי', 'אלמוג', 'ניר', 'ניב', 'נוער', 'פלג', 'שוהם', 'שלו', 'שמשון', 'צבי', 'אביב', 'עדן', 'מעיין', 'קשת', 'נוגה', 'שיר', 'תאיר', 'תכלת', 'תדהר', 'רקפת', 'כליל', 'טליה', 'מיכאלה', 'גבריאל', 'מלאכי', 'אלישע', 'איתי', 'עידו', 'סופיה', 'קלרה', 'אמה', 'אליס', 'אמיליה', 'אוליביה', 'לונה', 'לילי', 'ליאו', 'ליאון', 'ליאם', 'מקס', 'אנה', 'בלה', 'אווה', 'אוליבר', 'לוקה', 'מילה', 'נואה', 'ניקו', 'תיאה'
  );
